### ISSUE TITLE
Removing unecessary(?) unwraps()

### ISSUE THREAD

**Issue by LB767** [gwbres/cggtts#1]
I've noticed there's a bunch of `unwrap()` calls which, to my eye, seem quite bothering.
Especially when loading a CGGTTS file, the library will panic if the file isn't there or is malformed, which seems a bit exaggerated... (see [here](https://github.com/gwbres/cggtts/blob/ddb207fc728eb9987a493da0b84d003efbcb8930/cggtts/src/lib.rs#L635C8-L636C23) and [here](https://github.com/gwbres/cggtts/blob/ddb207fc728eb9987a493da0b84d003efbcb8930/cggtts/src/lib.rs#L644) for instance)

Any reason these were put in place? Could we not return an error?

**Comment by gwbres** [comment]
I just released your contribution as v3.2.1, both library and command line application.
